# Description: Common configuration all clients extend from.
# Configures ports and volumes for the client services.
# See: https://docs.docker.com/compose/how-tos/multiple-compose-files/extends/
services:
  base_client:
    ports:
      - "8551:8551"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ../jwt.hex:/config/jwt.hex
      - ../genesis.json:/config/genesis.json
      - ../chainspec.json:/config/chainspec.json
